### PR TITLE
The GUI part is sorted

### PR DESCRIPTION
**Pull request by DevanshD3**
This will read the values from the txt file and the values of initial and final theta and phi will be stored as an array

### CODE REVIEW

**Comment by Aviral09** [comment]
Please resolve the conflict

**Comment by DevanshD3** [comment]
How to see the conflict and remove it?

**Comment by Aviral09** [comment]
This time, I have resolved the conflicts for you. For future references, check this article out: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github

**Comment by DevanshD3** [comment]
Aah thanks bro!

**Pull request merged**
